// <auto-generated />
namespace EF2OR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AuditLogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuditLogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201606062111586_AuditLogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
